-- Energeia's PostgreSQL schema for Supabase.
-- Run this once in the Supabase SQL Editor for a new, empty project.
-- This script does not drop tables or saved records.

CREATE TABLE IF NOT EXISTS "Users" (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ElectricityRates" (
    rate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_name VARCHAR(150) NOT NULL,
    rate_per_kwh NUMERIC(10, 4) NOT NULL,
    effective_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "Households" (
    household_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    household_name VARCHAR(150) NOT NULL,
    address VARCHAR(255),
    rate_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_households_user FOREIGN KEY (user_id) REFERENCES "Users"(user_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_households_rate FOREIGN KEY (rate_id) REFERENCES "ElectricityRates"(rate_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_households_user ON "Households"(user_id);
CREATE INDEX IF NOT EXISTS idx_households_rate ON "Households"(rate_id);

CREATE TABLE IF NOT EXISTS "Appliances" (
    appliance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id INTEGER NOT NULL,
    appliance_name VARCHAR(150) NOT NULL,
    category VARCHAR(100),
    wattage NUMERIC(10, 2) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_appliances_household FOREIGN KEY (household_id) REFERENCES "Households"(household_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_appliances_household ON "Appliances"(household_id);

CREATE TABLE IF NOT EXISTS "UsageSchedules" (
    schedule_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appliance_id INTEGER NOT NULL,
    days_of_week VARCHAR(50) NOT NULL,
    hours_per_day NUMERIC(4, 2) NOT NULL,
    start_time TIME,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_schedules_appliance FOREIGN KEY (appliance_id) REFERENCES "Appliances"(appliance_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_schedules_appliance ON "UsageSchedules"(appliance_id);

CREATE TABLE IF NOT EXISTS "BillingRecords" (
    bill_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id INTEGER NOT NULL,
    rate_id INTEGER NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    total_kwh NUMERIC(10, 2),
    estimated_cost NUMERIC(10, 2),
    actual_bill_amount NUMERIC(10, 2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_billing_household FOREIGN KEY (household_id) REFERENCES "Households"(household_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_billing_rate FOREIGN KEY (rate_id) REFERENCES "ElectricityRates"(rate_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_billing_household ON "BillingRecords"(household_id);
CREATE INDEX IF NOT EXISTS idx_billing_rate ON "BillingRecords"(rate_id);
CREATE INDEX IF NOT EXISTS idx_billing_period ON "BillingRecords"(period_start, period_end);

CREATE TABLE IF NOT EXISTS "ConsumptionRecords" (
    record_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appliance_id INTEGER NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    estimated_kwh NUMERIC(10, 2),
    calculated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_consumption_appliance FOREIGN KEY (appliance_id) REFERENCES "Appliances"(appliance_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_consumption_appliance ON "ConsumptionRecords"(appliance_id);
CREATE INDEX IF NOT EXISTS idx_consumption_period ON "ConsumptionRecords"(period_start, period_end);

CREATE TABLE IF NOT EXISTS "WhatIfScenarios" (
    scenario_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id INTEGER NOT NULL,
    scenario_name VARCHAR(150) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_scenarios_household FOREIGN KEY (household_id) REFERENCES "Households"(household_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_scenarios_household ON "WhatIfScenarios"(household_id);

CREATE TABLE IF NOT EXISTS "ScenarioAppliances" (
    scenario_appliance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id INTEGER NOT NULL,
    appliance_id INTEGER NOT NULL,
    adjusted_hours_per_day NUMERIC(4, 2),
    adjusted_quantity INTEGER,
    CONSTRAINT fk_scenarioapp_scenario FOREIGN KEY (scenario_id)
        REFERENCES "WhatIfScenarios"(scenario_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_scenarioapp_appliance FOREIGN KEY (appliance_id) REFERENCES "Appliances"(appliance_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_scenarioapp_scenario ON "ScenarioAppliances"(scenario_id);
CREATE INDEX IF NOT EXISTS idx_scenarioapp_appliance ON "ScenarioAppliances"(appliance_id);

CREATE TABLE IF NOT EXISTS "Recommendations" (
    recommendation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id INTEGER NOT NULL,
    appliance_id INTEGER,
    message VARCHAR(500) NOT NULL,
    potential_savings_kwh NUMERIC(10, 2),
    potential_savings_cost NUMERIC(10, 2),
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_dismissed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_reco_household FOREIGN KEY (household_id) REFERENCES "Households"(household_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_reco_appliance FOREIGN KEY (appliance_id) REFERENCES "Appliances"(appliance_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_reco_household ON "Recommendations"(household_id);
CREATE INDEX IF NOT EXISTS idx_reco_appliance ON "Recommendations"(appliance_id);

-- This is a deliberately unconfigured rate, not an assumed real electricity tariff.
INSERT INTO "ElectricityRates" (provider_name, rate_per_kwh, effective_date)
SELECT 'Set your provider', 0, CURRENT_DATE
WHERE NOT EXISTS (
    SELECT 1 FROM "ElectricityRates" WHERE provider_name = 'Set your provider'
);

-- The API connects with the private database connection string. Keep direct
-- Supabase Data API access to these tables disabled unless policies are added.
ALTER TABLE "Users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ElectricityRates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Households" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Appliances" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UsageSchedules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BillingRecords" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ConsumptionRecords" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WhatIfScenarios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ScenarioAppliances" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Recommendations" ENABLE ROW LEVEL SECURITY;
